name: 'Merge develop_mk to main'

on: 
    push: 
        branches: ["develop_mk"]
    

jobs: 
    merge-develop_mk-to-main:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4
            - name: Merge develop_mk to main
              run: |
                git checkout main
                git pull origin main
                git merge develop_mk 
                git push origin main
            
            - name: Success Push 
              run: echo "Success Push" 