name: 'Merge develop_mk to main'

on: 
    push: 
        branches: ["develop_mk"]
    

jobs: 
    merge-develop_mk-to-main:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4
            - name: Merge develop_mk to main
              run: |
                DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
                git checkout $DEFAULT_BRANCH
                git pull origin $DEFAULT_BRANCH
                git merge develop_mk 
                git push origin $DEFAULT_BRANCH
            
            - name: Success Push 
              run: echo "Success Push" 